/**
 * High Level Design Compiler for Altera(R) FPGAs Version 26.1 (Release Build #805d06383c)
 * Software model created on 2026-08-25 13:21:30
 * Generation mode: Bit Accurate
 */
#if defined(CSL_USE_PRAGMA_ONCE)
#pragma once
#endif

#ifndef SOFTWARE_MODEL_IFFT8K_BASE_DUTATB_H_
#define SOFTWARE_MODEL_IFFT8K_BASE_DUTATB_H_

#include "ifft8k_base_DUT.h"

/**
 * Automated Test Bench (ATB) for ifft8k_base_DUT
 * 
 * This class provides automated testing capabilities for the generated model by:
 * - Reading input stimulus from .stm files generated by the Simulink simulation
 * - Driving the model with test vectors
 * - Capturing and comparing output against the output .stm files from the Simulink simulation
 */
class ifft8k_base_DUTATB
{
public:
    /**
     * Reads input data from a stimulus file into an io_struct_ChannelIn
     * 
     * @param stm The stimulus file to read from
     * @param value_out The structure to populate with values from the stimulus file
     */
    void read_from_stm(csl::stimulus_file& stm, ifft8k_base_DUT::io_struct_ChannelIn& value_out)
    {
        stm.get(value_out.port_v_in_s, 1);
        stm.skip(1);
        stm.get(value_out.port_data_in_0re);
        stm.get(value_out.port_data_in_0im);
        stm.get(value_out.port_data_in_1re);
        stm.get(value_out.port_data_in_1im);
        stm.get(value_out.port_data_in_2re);
        stm.get(value_out.port_data_in_2im);
        stm.get(value_out.port_data_in_3re);
        stm.get(value_out.port_data_in_3im);
    }

    /**
     * Instantiates the model
     */ 
    ifft8k_base_DUTATB()
    {
        m_model = new ifft8k_base_DUT();
    }
    /**
     * Deletes the model
     */ 
    ~ifft8k_base_DUTATB()
    {
        delete m_model;
    }
    /**
     * ATB classes may not be copied, moved or assigned.
     */ 
    ifft8k_base_DUTATB(const ifft8k_base_DUTATB&) = delete;
    ifft8k_base_DUTATB(ifft8k_base_DUTATB&&) = delete;
    ifft8k_base_DUTATB& operator=(const ifft8k_base_DUTATB&) = delete;
    ifft8k_base_DUTATB& operator=(ifft8k_base_DUTATB&&) = delete;

    /**
     * Executes the simulation testbench:
     * 
     *   1. Resets the model to initial state
     *   2. Opens and reads input stimulus files
     *   3. Drives the model with each line of stimulus data
     *   4. Captures output data and write .stm file
     * 
     * The output .stm file names will exactly match those from the Simulink simulation.
     * 
     * @return true if all input stimulus files were opened and no fatal errors occurred
     *              during simulation. Non-fatal errors are reported later.
     * @return false if any file I/O errors occurred
     * 
     * NOTE: output comparison is performed separately via compare(), the full simulation.
     * always runs.
     */
    bool run()
    {
        bool all_inputs_opened = true;
        ifft8k_base_DUT* model_instance = new ifft8k_base_DUT();
        model_instance->reset();
        model_instance->open_stimulus_files();
        csl::info("[ifft8k_base_DUT] Opening input stimulus files...");
        csl::stimulus_file io_struct_ChannelIn_stm_in0("../ifft8k_base_DUT_ChannelIn_vunroll_cunroll_x.stm", csl::stimulus_format::SIGNED);
        all_inputs_opened &= io_struct_ChannelIn_stm_in0.is_open();
        if (all_inputs_opened)
        {
            csl::info("[ifft8k_base_DUT] Simulating...");
            while(io_struct_ChannelIn_stm_in0.next_line())
            {
                ifft8k_base_DUT::io_struct_ChannelIn io_struct_ChannelIn0 {};
                read_from_stm(io_struct_ChannelIn_stm_in0, io_struct_ChannelIn0);
                model_instance->write(io_struct_ChannelIn0);
                ifft8k_base_DUT::io_struct_ChannelOut io_struct_ChannelOut0 {};
                model_instance->read(io_struct_ChannelOut0);
            }
        }
        delete model_instance;
        if (all_inputs_opened)
        {
            csl::info("[ifft8k_base_DUT] Simulation has completed.");
        }
        else
        {
            csl::error("[ifft8k_base_DUT] Simulation failure! Stimulus file IO errors occurred.");
        }
        return all_inputs_opened;
    }

    /**
     * Compares the output .stm files generated during run() against 
     * reference output files from Simulink to verify correctness
     * of the software model.
     * 
     * @return true if all outputs match expected values
     * @return false if any output mismatches are detected
     * 
     * @note This should be called only after run() completes successfully
     */
    bool compare()
    {
        bool success = true;
        success &= csl::compare_stm_files("ifft8k_base_DUT_ChannelOut_vunroll_cunroll_x.stm", "../ifft8k_base_DUT_ChannelOut_vunroll_cunroll_x.stm");
        return success;
    }

private:
    ifft8k_base_DUT* m_model;
};

#endif // SOFTWARE_MODEL_IFFT8K_BASE_DUTATB_H_

