// ----------------------------------------------------------------------
// Layout MUST match the software-model ABI exactly (see
// fhe_ifft_8k_4lanes_double_261_sycl.hpp, generated by the HLS compiler):
//   int8_t port_v_in_s; double re0; double im0; ... double im3;
// That's 1 + 8*8 = 65 bytes = 520 bits, packed with no gaps. The XML
// manifest declares idata/odata as 528 bits (520 rounded up to a nicer
// bus width), so there are 8 real, genuinely-unused padding bits -- and
// they belong at the very top (above the first double), NOT between the
// doubles and the valid bit. An earlier version of this file put a named
// "channel_in_s"/blank field in that gap instead of real padding at the
// top, which silently shifted every double field by one byte relative to
// the real ABI (invisible in tests with all-zero imaginary data, since
// the resulting garbage byte happened to be zero -- but wrong in
// general). channel_in_s IS a real port on the underlying VHDL DUT
// (std_logic_vector(7 downto 0)), but it is NOT part of the
// software-visible ABI at all, so it cannot be sliced out of idata; it
// is tied to a constant below instead. (Same fix as the 4K design's
// fhe_ifft_4k_4lanes_double_253_module.sv -- see that file's header for
// the original discovery.)
// ----------------------------------------------------------------------

typedef struct packed {
    logic[7:0] ChannelIn_pad_unused; // real padding: 528 (declared bus width) - 520 (actual ABI) = 8 bits
    logic[63:0] ChannelIn_port_data_in_3im;
    logic[63:0] ChannelIn_port_data_in_3re;
    logic[63:0] ChannelIn_port_data_in_2im;
    logic[63:0] ChannelIn_port_data_in_2re;
    logic[63:0] ChannelIn_port_data_in_1im;
    logic[63:0] ChannelIn_port_data_in_1re;
    logic[63:0] ChannelIn_port_data_in_0im;
    logic[63:0] ChannelIn_port_data_in_0re;
    logic[7:0] ChannelIn_port_v_in_s;
} input_t;

typedef struct packed {
    logic[7:0] ChannelOut_pad_unused; // see ChannelIn_pad_unused above
    logic[63:0] ChannelOut_port_data_out_3im;
    logic[63:0] ChannelOut_port_data_out_3re;
    logic[63:0] ChannelOut_port_data_out_2im;
    logic[63:0] ChannelOut_port_data_out_2re;
    logic[63:0] ChannelOut_port_data_out_1im;
    logic[63:0] ChannelOut_port_data_out_1re;
    logic[63:0] ChannelOut_port_data_out_0im;
    logic[63:0] ChannelOut_port_data_out_0re;
    logic[7:0] ChannelOut_port_v_out_s;
} output_t;

// ----------------------------------------------------------------------
// This DUT is NOT a fixed-latency component: on the input side it
// tolerates bubbles (v_in_s=0 is safe at any time; no state corruption),
// accumulates one full frame (NUM_BLOCKS beats), and only then starts
// computing -- while simultaneously allowing a *second* frame's input to
// begin filling behind it (2-deep, double-buffered pipelining). Once a
// frame's computation completes, its result appears as a burst of
// NUM_BLOCKS consecutive valid output beats. Because the delay between
// "last valid input" and "first valid output" is not a static number of
// cycles, this cannot be honestly described to the offline compiler via
// IS_STALL_FREE="yes"/EXPECTED_LATENCY (see the companion .xml, which now
// sets IS_STALL_FREE="no"). Instead, this wrapper implements real, live
// ivalid/iready/ovalid/oready handshaking:
//
//   - Output side: an internal show-ahead (FWFT) FIFO decouples the
//     DUT's raw one-burst-per-frame v_out_s timing from the
//     compiler-visible ovalid/oready/odata interface. ovalid is simply
//     "FIFO not empty"; a beat is consumed exactly when ovalid && iready.
//     The FIFO is sized for 2 full frames (2 x NUM_BLOCKS beats), which
//     is the worst case of 2 completely computed, fully undrained frames
//     sitting in the FIFO at once.
//
//   - Input side: since the DUT can have at most 2 frames in flight (one
//     draining/computing, one being fed), the wrapper tracks frame-level
//     admission/drain counts and only asserts oready while fewer than 2
//     frames' worth of future output are outstanding. This guarantees
//     the output FIFO can never overflow, and that we never violate the
//     DUT's own 2-deep pipelining limit. Gating applies uniformly to
//     every beat (not just frame-start beats): dropping oready mid-frame
//     just produces a bubble on the DUT's v_in_s, which the DUT is
//     documented to tolerate.
// ----------------------------------------------------------------------

module fhe_ifft_8k_4lanes_double_261_module
(
    input  clock,
    input  resetn,

    input  ivalid,
    output ovalid,

    input  iready,
    output oready,

    input[$bits(input_t) - 1:0] idata,
    output[$bits(output_t) - 1:0] odata
);

localparam int NUM_BLOCKS = 2048; // 8192-point IFFT / 4 lanes per beat
localparam int FRAMES_IN_FLIGHT_MAX = 2; // DUT's own double-buffered input limit
localparam int FIFO_DEPTH = FRAMES_IN_FLIGHT_MAX * NUM_BLOCKS; // 4096 beats = 2 full IFFTs
localparam int FIFO_ADDR_W = $clog2(FIFO_DEPTH);
localparam int BEAT_CNT_W = $clog2(NUM_BLOCKS);
localparam int DATA_W = $bits(output_t);

input_t dataIn;
output_t dataOut;

logic valid_in;
logic valid_out;
logic areset;

assign dataIn = idata;

assign valid_in = ivalid & oready & dataIn.ChannelIn_port_v_in_s;

// ifft8k_base_DUT.v_out_s is a 1-bit RTL port (see ifft8k_base_DUT.vhd:
// "v_out_s : out std_logic_vector(0 downto 0)"), but ChannelOut_port_v_out_s
// is packed as a full byte in the co-sim struct to match the byte-aligned
// int8_t field in the C++/SYCL software model. Zero-extend explicitly rather
// than leaving the upper 7 bits of the struct field undriven. Any entry
// that made it into the output FIFO is, by construction, a real beat, so
// this field always reads back as 1 downstream of the FIFO.
assign dataOut.ChannelOut_port_v_out_s = {7'b0, valid_out};

// Genuinely unused padding bits (see struct comment above) -- must still
// be explicitly driven since dataOut is assembled field-by-field, and a
// packed struct with any undriven bits reads back as X in simulation.
assign dataOut.ChannelOut_pad_unused = 8'b0;

assign areset = resetn;

ifft8k_base_DUT
ifft8k_base_DUT_inst (
    .v_in_s (valid_in),
    // channel_in_s is a real DUT port but is NOT part of the
    // software-visible idata ABI (see struct comment above); this
    // single-channel instantiation ties it to a fixed value.
    .channel_in_s (8'b0),
    .data_in_0re (dataIn.ChannelIn_port_data_in_0re),
    .data_in_0im (dataIn.ChannelIn_port_data_in_0im),
    .data_in_1re (dataIn.ChannelIn_port_data_in_1re),
    .data_in_1im (dataIn.ChannelIn_port_data_in_1im),
    .data_in_2re (dataIn.ChannelIn_port_data_in_2re),
    .data_in_2im (dataIn.ChannelIn_port_data_in_2im),
    .data_in_3re (dataIn.ChannelIn_port_data_in_3re),
    .data_in_3im (dataIn.ChannelIn_port_data_in_3im),
    .v_out_s (valid_out),
    .data_out_0re (dataOut.ChannelOut_port_data_out_0re),
    .data_out_0im (dataOut.ChannelOut_port_data_out_0im),
    .data_out_1re (dataOut.ChannelOut_port_data_out_1re),
    .data_out_1im (dataOut.ChannelOut_port_data_out_1im),
    .data_out_2re (dataOut.ChannelOut_port_data_out_2re),
    .data_out_2im (dataOut.ChannelOut_port_data_out_2im),
    .data_out_3re (dataOut.ChannelOut_port_data_out_3re),
    .data_out_3im (dataOut.ChannelOut_port_data_out_3im),
    .clk (clock),
    .areset (areset)
);

// ----------------------------------------------------------------------
// Output-side FIFO (show-ahead / first-word-fall-through, 2 frames deep).
// Pushed unconditionally whenever the DUT asserts valid_out -- this write
// must never be refused; the admission control below guarantees room
// always exists by the time any given frame's output burst lands. Popped
// exactly on a genuine downstream transfer (ovalid && iready).
//
// Backed by the Quartus `scfifo` LPM megafunction (lpm_showahead="ON",
// matching the FWFT semantics already documented above: q/empty are
// valid at the head of the queue with no separate rdreq-then-wait step)
// with use_eab="ON" to force real M20K block-RAM storage, rather than a
// hand-rolled packed-array FIFO with a combinational
// `fifo_mem[fifo_rd_ptr]` read (the previous version of this block) --
// see the_nwc_8k_ntt_module.sv's matching comment for why that pattern is
// a real fMAX/area risk at 4096 entries on actual hardware, even though
// it is functionally correct in simulation. intended_device_family is
// left at the same placeholder this build's own AOC-generated FIFOs use
// (Quartus auto-corrects it to the real target device); overflow/
// underflow checking are safely "OFF" since the admission control below
// already guarantees, by construction, the FIFO is never pushed while
// full or popped while empty.
// ----------------------------------------------------------------------

logic fifo_push;
logic fifo_pop;
logic fifo_empty;
logic [FIFO_ADDR_W-1:0] fifo_usedw;

assign fifo_push  = valid_out;
assign ovalid     = ~fifo_empty;
assign fifo_pop   = ovalid & iready;

scfifo #(
    .lpm_width               (DATA_W),
    .lpm_widthu              (FIFO_ADDR_W),
    .lpm_numwords            (FIFO_DEPTH),
    .lpm_showahead           ("ON"),
    .lpm_type                ("scfifo"),
    .lpm_hint                ("USE_EAB=ON"),
    .intended_device_family  ("Stratix 10"),
    .overflow_checking       ("OFF"),
    .underflow_checking      ("OFF"),
    .use_eab                 ("ON"),
    .add_ram_output_register ("OFF")
) ifft_output_fifo (
    .data         (dataOut),
    .clock        (clock),
    .wrreq        (fifo_push),
    .rdreq        (fifo_pop),
    .aclr         (1'b0),
    .sclr         (~resetn),
    .q            (odata),
    .usedw        (fifo_usedw),
    .full         (),
    .empty        (fifo_empty),
    .almost_full  (),
    .almost_empty ()
);

// ----------------------------------------------------------------------
// Input-side admission control: track how many complete NUM_BLOCKS-beat
// frames have been admitted into the DUT but not yet fully drained from
// the output FIFO ("frames in flight"), and deassert oready once
// FRAMES_IN_FLIGHT_MAX are outstanding.
// ----------------------------------------------------------------------

logic [BEAT_CNT_W-1:0] admit_beat_cnt;
logic [BEAT_CNT_W-1:0] drain_beat_cnt;
logic [1:0] frames_admitted;
logic [1:0] frames_drained;
logic [1:0] frames_in_flight;

assign frames_in_flight = frames_admitted - frames_drained;
assign oready = (frames_in_flight < FRAMES_IN_FLIGHT_MAX);

always_ff @(posedge clock) begin
    if (!resetn) begin
        admit_beat_cnt  <= '0;
        drain_beat_cnt  <= '0;
        frames_admitted <= '0;
        frames_drained  <= '0;
    end else begin
        if (valid_in) begin
            if (admit_beat_cnt == NUM_BLOCKS - 1) begin
                admit_beat_cnt  <= '0;
                frames_admitted <= frames_admitted + 1'b1;
            end else begin
                admit_beat_cnt <= admit_beat_cnt + 1'b1;
            end
        end
        if (fifo_pop) begin
            if (drain_beat_cnt == NUM_BLOCKS - 1) begin
                drain_beat_cnt <= '0;
                frames_drained <= frames_drained + 1'b1;
            end else begin
                drain_beat_cnt <= drain_beat_cnt + 1'b1;
            end
        end
    end
end

// synthesis translate_off
// TEMPORARY DIAGNOSTIC: mirrors the_nwc_8k_ntt_module.sv's NTT_DBG print
// exactly, unconditional (every cycle, not gated on ivalid/valid_in), so
// we can directly compare IFFT's real ivalid behavior against NTT's on an
// apples-to-apples basis -- specifically, whether ivalid ever reads 0
// while dataIn.ChannelIn_port_v_in_s is also 0 (i.e. during a genuine
// upstream idle/empty-pipe cycle), the way NTT's ivalid does NOT.
always_ff @(posedge clock) begin
    if (resetn) begin
        $display("IFFT_DBG t=%0t in_beat=%0d ivalid=%b iready=%b oready=%b valid_in=%b v_in_s=%b frames_in_flight=%0d",
            $time, admit_beat_cnt, ivalid, iready, oready, valid_in,
            dataIn.ChannelIn_port_v_in_s[0], frames_in_flight);
        if (valid_out) begin
            $display("IFFT_DBG t=%0t out_beat=%0d fifo_usedw=%0d", $time, drain_beat_cnt, fifo_usedw);
        end
    end
end
// synthesis translate_on

endmodule;
